# ---------------------------------------------------------------------------------------------
# カラースキーマ
# ---------------------------------------------------------------------------------------------

[[plugins]]
repo = 'cocopon/iceberg.vim'


#---------------------------------------------
# プラットフォーム系
# 他のプラグインが動く基盤となる.
#---------------------------------------------

[[plugins]]
# lazy非推奨なのでこちらに
repo ='williamboman/mason.nvim'
on_event = ["BufRead"]
# on_source = 'nvim-lspconfig'
hook_source = '''
lua << EOF
require("mason").setup({
  ui = {
    icons = {
      package_installed = "✓",
      package_pending = "➜",
      package_uninstalled = "✗"
    }
  }
})
EOF
'''

[[plugins]]
# lua系プラグインのutility関数
repo = 'nvim-lua/plenary.nvim'


# ---------------------------------------------------------------------------------------------
# ファイル/テキスト編集補助ツール.
# ---------------------------------------------------------------------------------------------

[[plugins]]
# "や(などのペアを自動補完する.
repo = 'cohama/lexima.vim' # TODO: not lazyに記述している理由を調査.
# hook_add = '''
# let g:lexima_enable_newline_rules = 0
# '''

[[plugins]]
# 区切り文字で整形
# alip=  段落を対象に=で位置を整形 -> aで待ちが発生するし複雑だから止めた.
# alip*| 段落を対象に同列内の全ての|の位置を整形, テーブル表記とか -> aで待ちが発生するし複雑だから止めた.
# 選択-> al -> =入力  選択範囲で=位置で整形
repo = 'junegunn/vim-easy-align' # TODO: not lazyに記述している理由を調査.
hook_add = '''
" xmap al <Plug>(EasyAlign)
" nmap al <Plug>(EasyAlign)
vmap al <Plug>(EasyAlign)
'''

