[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add = '''
let g:tokyonight_style = "night"
'''

# [[plugins]]
# # マルチカーソル
# repo = 'mg979/vim-visual-multi'

[[plugins]]
# "や(などのペアを自動補完する.
repo = 'cohama/lexima.vim'
# hook_add = '''
# let g:lexima_enable_newline_rules = 0
# '''

[[plugins]]
# 区切り文字で整形
# alip=  段落を対象に=で位置を整形 -> aで待ちが発生するし複雑だから止めた.
# alip*| 段落を対象に同列内の全ての|の位置を整形, テーブル表記とか -> aで待ちが発生するし複雑だから止めた.
# 選択-> al -> =入力  選択範囲で=位置で整形
repo = 'junegunn/vim-easy-align'
hook_add = '''
" xmap al <Plug>(EasyAlign)
" nmap al <Plug>(EasyAlign)
vmap al <Plug>(EasyAlign)
'''

# [[plugins]]
# repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# [[plugins]] # TODO: 暫定的に削除.
# repo = 'nvim-telescope/telescope.nvim'
# hook_add = '''
# " Find files using Telescope command-line sugar.
# nnoremap <leader>ff <cmd>Telescope find_files<cr>
# nnoremap <leader>fg <cmd>Telescope live_grep<cr>
# nnoremap <leader>fb <cmd>Telescope buffers<cr>
# nnoremap <leader>fh <cmd>Telescope help_tags<cr>
# 
# " "" Using Lua functions
# " "nnoremap <leader>ff <cmd>lua require('telescope.builtin').find_files()<cr>
# " "nnoremap <leader>fg <cmd>lua require('telescope.builtin').live_grep()<cr>
# " "nnoremap <leader>fb <cmd>lua require('telescope.builtin').buffers()<cr>
# " "nnoremap <leader>fh <cmd>lua require('telescope.builtin').help_tags()<cr>
# '''

# [[plugins]]
# repo = 'airblade/vim-gitgutter'
# 
# [[plugins]]
# repo = 'tpope/vim-fugitive'
# 
# [[plugins]]
# # 文字検索時マッチング個数と何番目かを表示するプラグイン
# repo = 'osyo-manga/vim-anzu'
# hook_add = '''
# nmap n <Plug>(anzu-n-with-echo)
# nmap N <Plug>(anzu-N-with-echo)
# nmap * <Plug>(anzu-star-with-echo)
# nmap # <Plug>(anzu-sharp-with-echo)
# '''
# #nmap <Esc><Esc> <Plug>(anzu-clear-search-status)#効かない？
# 
# [[plugins]]
# # 多形式対応のシンタックスハイライト
# repo = 'sheerun/vim-polyglot'
# 
# [[plugins]]
# # インデントの可視化
# repo = 'Yggdroot/indentLine'
# 
# [[plugins]]
# # 行末空白の可視化
# repo = 'bronson/vim-trailing-whitespace'
# 
# [[plugins]]
# # 画面スクロール過程を可視化
# repo = 'yuttie/comfortable-motion.vim'
# 
# [[plugins]]
# # ウィンドウサイズ変更の簡易化
# repo = 'simeji/winresizer'
# hook_add = '''
# let g:winresizer_vert_resize = 2
# let g:winresizer_horiz_resize = 1
# '''
# 
# [[plugins]]
# # ウィンドウのひとつを最大化
# # 動くけどエラーがたくさんでる.NeoVim未対応？
# repo = 'vim-scripts/ZoomWin'
# 
# [[plugins]]
# # チートシート表示
# repo = 'reireias/vim-cheatsheet'
# hook_add = '''
# let g:cheatsheet#cheat_file = '~/.cheetsheets/sample.md'
# let g:cheatsheet#float_window = 1
# " you can change float window size.
# let g:cheatsheet#float_window_width_ratio = 0.6
# let g:cheatsheet#float_window_height_ratio = 0.6
# '''
# #augroup vimrc_filetype
# #  autocmd!
# #  autocmd FileType zsh let g:cheatsheet#cheat_file = '~/.cheatsheet-zsh.md'
# #augroup END


#---------------------------------------------
# LSP関連(masonがlazy非推奨なので全てこちらに
#---------------------------------------------

[[plugins]]
repo ='williamboman/mason.nvim'
on_event = ["BufRead"]
# on_source = 'nvim-lspconfig'
hook_source = '''
lua << EOF
require("mason").setup({
  ui = {
    icons = {
      package_installed = "✓",
      package_pending = "➜",
      package_uninstalled = "✗"
    }
  }
})
EOF
'''

